import { useEffect, useState } from 'react';
import { api } from '../api/client';
import type { DashboardStats, MnoTransaction, MnoWallet, TransactionType } from '../api/types';
import { DashboardKPICard } from '../components/DashboardKPICard';
import { Modal } from '../components/Modal';
const blank = { walletId: 0, transactionType: 'DEPOSIT' as TransactionType, amount: 0, agentNumber: '', clientPhone: '', clientName: '' };
export function MNOWalletTransactionsPage() {
  const [wallets, setWallets] = useState<MnoWallet[]>([]); const [items, setItems] = useState<MnoTransaction[]>([]); const [stats, setStats] = useState<DashboardStats | null>(null); const [edit, setEdit] = useState<typeof blank | null>(null); const [message, setMessage] = useState('');
  const load = () => { api.wallets().then(setWallets); api.transactions().then(setItems); api.dashboard().then(setStats); }; useEffect(load, []);
  async function save() { if (!edit) return; setMessage(''); try { await api.recordTransaction(edit); setMessage('Transaction recorded'); setEdit(null); load(); } catch (err) { setMessage('Transaction failed'); } }
  return <section><div className="sectionHead"><h1>Transactions</h1><button onClick={()=>setEdit({...blank, walletId: wallets[0]?.id ?? 0})}>Record Transaction</button></div><div className="kpis"><DashboardKPICard label="Transactions" value={stats?.transactionCount ?? 0}/><DashboardKPICard label="Wallet balance" value={stats?.totalWalletBalance ?? 0}/></div>{message && <p className="notice">{message}</p>}<div className="table">{items.map(t => <div className="row" key={t.id}><span>{new Date(t.date).toLocaleString()}</span><span>{t.mnoWalletName}</span><span>{t.transactionType}</span><span>{t.amount}</span><span>{t.status}</span><span>{t.balance}</span></div>)}</div>{edit && <Modal title="Record Transaction" onClose={()=>setEdit(null)} onSubmit={e=>{e.preventDefault(); save();}}><label>Wallet<select value={edit.walletId} onChange={e=>setEdit({...edit,walletId:+e.target.value})}>{wallets.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label>Type<select value={edit.transactionType} onChange={e=>setEdit({...edit,transactionType:e.target.value as TransactionType})}><option>DEPOSIT</option><option>WITHDRAWAL</option></select></label><label>Amount<input type="number" value={edit.amount} onChange={e=>setEdit({...edit,amount:+e.target.value})}/></label><label>Agent number<input value={edit.agentNumber} onChange={e=>setEdit({...edit,agentNumber:e.target.value})}/></label><label>Client phone<input value={edit.clientPhone} onChange={e=>setEdit({...edit,clientPhone:e.target.value})}/></label><label>Client name<input value={edit.clientName} onChange={e=>setEdit({...edit,clientName:e.target.value})}/></label></Modal>}</section>;
}
